baseURL = 'https://example.org/'
languageCode = 'es'
title = '~/home/zodac'
disableKinds = ['taxonomy', 'term']

[[menu.main]]
    name = 'inicio'
    url = '/'
    weight = 1
[[menu.main]]
    name = 'blog'
    url = '/blog'
    weight = 2

[params]
    subtitle = 'bienvenido a mi espacio virtual'

[markup]
    [markup.highlight]
        style = "gruvbox"
